//! `commitbook-client`, UniFFI SDK exposing `CommitBookEngineClient` to
//! native iOS/macOS/Android apps. Wraps `commitbook-engine` orchestration.
//!
//! UDL spec: `crates/commitbook-client/src/commitbook.udl`.

// UniFFI scaffolding generated by `include_scaffolding!` below defines a large
// `const` metadata buffer; the generated file cannot carry its own attribute.
#![allow(clippy::large_const_arrays)]

mod auth;
mod client;
mod commitbooks_ops;
mod conflicts;
mod credentials;
mod documents;
mod errors;
mod paths;
mod runtime;
mod sync_ops;
mod types;

pub use client::*;
pub use errors::*;
pub use types::*;

uniffi::include_scaffolding!("commitbook");

#[cfg(test)]
mod test_support {
    pub fn set_identity(root: &std::path::Path) {
        commitbook_engine::commitbooks::identity::ensure(root).unwrap();
        std::fs::write(
            commitbook_engine::commitbooks::identity::path(root),
            "commitbook_local_id = \"a1b2c3d4\"\n",
        )
        .unwrap();
    }
}
