[workspace]
members = [
    "crates/commitbook-engine",
    "crates/commitbook-cli",
    "crates/commitbook-tui",
    "crates/commitbook-web",
    "crates/commitbook-client",
]
resolver = "2"

[workspace.package]
rust-version = "1.91"
version = "0.9.0"
edition = "2021"
license = "MIT"
authors = ["ZAAI"]

[profile.release]
strip = true
lto = true
opt-level = "z"
