[workspace]
members = [
    "crates/commitbook-core",
    "crates/commitbook-cli",
    "crates/commitbook-tui",
    "crates/commitbook-web",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["ZAAI"]

[profile.release]
strip = true
lto = true
opt-level = "z"
