package cmd

import (
	"fmt"
	"os"
	"syscall"
	"time"

	"github.com/ZAAI-com/CommitBook/internal/ai"
	"github.com/ZAAI-com/CommitBook/internal/config"
	"github.com/ZAAI-com/CommitBook/internal/gitops"
	"github.com/ZAAI-com/CommitBook/internal/logger"
	"github.com/spf13/cobra"
)

var runCmd = &cobra.Command{
	Use:    "run",
	Short:  "Execute a single auto-commit cycle",
	Long:   `Performs a single auto-commit cycle: check for changes, generate commit message, commit, and push. This command is called by launchd and is not intended for direct use.`,
	Hidden: true,
	RunE:   runAutoCommit,
}

func init() {
	rootCmd.AddCommand(runCmd)
}

func runAutoCommit(cmd *cobra.Command, args []string) error {
	repoDir, err := config.ResolveRepoPath(repoPath)
	if err != nil {
		return fmt.Errorf("resolving repo path: %w", err)
	}

	// Load repo config
	repoCfg, err := config.LoadRepoConfig(repoDir)
	if err != nil {
		return err
	}

	// Initialize logger
	log, err := logger.New(repoDir, repoCfg.Logging.MaxLogDays)
	if err != nil {
		return fmt.Errorf("initializing logger: %w", err)
	}

	// Acquire file lock
	lockPath := config.RepoLockPath(repoDir)
	lockFile, err := os.OpenFile(lockPath, os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Error(fmt.Sprintf("Cannot create lock file: %v", err))
		return err
	}
	defer lockFile.Close()
	defer os.Remove(lockPath)

	if err := syscall.Flock(int(lockFile.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		log.Info("Another instance is running, skipping")
		return nil
	}
	defer syscall.Flock(int(lockFile.Fd()), syscall.LOCK_UN)

	// Check if enabled
	if !repoCfg.Enabled {
		log.Info("CommitBook is disabled, skipping")
		return nil
	}

	log.Info("Auto-commit cycle started")

	// Check for changes
	summary, err := gitops.Status(repoDir)
	if err != nil {
		log.Error(fmt.Sprintf("Git status failed: %v", err))
		return err
	}

	if summary.IsClean() {
		log.Info("No changes detected, skipping")
		return nil
	}

	log.Info(fmt.Sprintf("Changes detected: %s", summary.String()))

	// Stage all changes
	if err := gitops.StageAll(repoDir); err != nil {
		log.Error(fmt.Sprintf("Git add failed: %v", err))
		return err
	}

	// Load AI provider list from global config
	globalCfg, err := config.LoadGlobalConfig()
	providers := []string{"gh-copilot", "claude-cli", "codex-cli", "fallback"}
	if err == nil && len(globalCfg.AI.Providers) > 0 {
		providers = globalCfg.AI.Providers
	}

	// Generate commit message
	message, providerName := ai.GenerateCommitMessage(summary, providers, repoDir)
	log.Info(fmt.Sprintf("Commit message generated by %s: %s", providerName, message))

	// Commit
	hash, err := gitops.Commit(repoDir, message)
	if err != nil {
		log.Error(fmt.Sprintf("Git commit failed: %v", err))
		return err
	}
	log.Info(fmt.Sprintf("Committed: %s", hash))

	// Push if auto-push is enabled
	if repoCfg.Git.AutoPush {
		if err := gitops.Push(repoDir, "origin", repoCfg.Git.Branch); err != nil {
			log.Warn(fmt.Sprintf("Git push failed (will retry next cycle): %v", err))
			// Don't return error — commit succeeded, push can retry
		} else {
			log.Info(fmt.Sprintf("Pushed to origin/%s", repoCfg.Git.Branch))
		}
	}

	// Update last commit timestamp
	repoCfg.LastCommit = time.Now().UTC().Format(time.RFC3339)
	if err := config.SaveRepoConfig(repoDir, repoCfg); err != nil {
		log.Warn(fmt.Sprintf("Failed to update last_commit: %v", err))
	}

	// Cleanup old logs
	if err := log.Cleanup(); err != nil {
		log.Warn(fmt.Sprintf("Log cleanup failed: %v", err))
	}

	log.Info("Auto-commit cycle completed")
	return nil
}
